In [2]:
import random
x=random.randint(1,100)
print(x)

58


In [3]:
x=random.randint(1,100)

In [4]:
print(x)

52


In [5]:
import numpy as np
x=np.array(100)
print(x)

100


CELDAS DE TEXTO
Esta celda es de Texto

In [7]:
import numpy as np
escalar=np.array(10)
vector=np.array([1,3,5,7,9])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
tensor=np.array([[[1,2],[3,4],[5,6]]])

In [8]:
print(escalar)
print(vector)
print(matrix)
print(tensor)

10
[1 3 5 7 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]
  [5 6]]]


In [9]:
tensor=np.array([
    [[[1,2],[3,4],[5,6]]],
	[[[1,2],[3,4],[5,6]]],
	[[[1,2],[3,4],[5,6]]]
])

tensor

array([[[[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]]]])

In [10]:
print(tensor)

[[[[1 2]
   [3 4]
   [5 6]]]


 [[[1 2]
   [3 4]
   [5 6]]]


 [[[1 2]
   [3 4]
   [5 6]]]]


In [11]:
ceros=np.zeros((3,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
unos=np.ones((4,4))
unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
v1=np.arange(9)
v1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
v2=np.arange(10,100)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [15]:
v3=np.arange(10,100,10)
v3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
import random
lista=[random.randint(1,100) for i in range(random.randint(5,15))]
lista


[61, 98, 61, 56, 84, 47, 51, 14, 87, 58, 69, 53, 85, 87, 17]

In [17]:
vector=np.array(lista)
vector

array([61, 98, 61, 56, 84, 47, 51, 14, 87, 58, 69, 53, 85, 87, 17])

In [18]:
x=random.random()
x=int(x*100)
x

36

In [19]:
#tam=int(input("ingrese cantidad"))
vec=np.random.randint(1,100,size=(1,random.randint(5,15)))
vec

array([[ 8, 74, 60, 82, 54, 17, 58, 97]])

In [20]:
arreglo=np.arange(6)
nuevo=arreglo.reshape(3,2)
nuevo

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
arreglo=np.arange(6)
arreglo=np.append(arreglo,22)
arreglo

array([ 0,  1,  2,  3,  4,  5, 22])

In [22]:
print(arreglo.size)

7


In [23]:
lista=[random.randint(1,100) for i in range(random.randint(5,15))]
lista
npvec=np.array(lista)
npvec



array([ 81,  25, 100,  72,  25,  61,  56,  36,  60,  76])

In [24]:
npvec[:int(npvec.size/2):3]

array([81, 72])

In [25]:
npvec[int(npvec.size/2)::2]

array([61, 36, 76])

In [26]:
lista[::2]

[81, 100, 25, 56, 60]

In [27]:
lista[8:]

[60, 76]

In [28]:
lista[-1:-5:-1]

[76, 60, 36, 56]

In [29]:
matrix=np.random.randint(1,100,size=(5,5))
matrix

array([[72, 74, 56,  3, 73],
       [45, 94, 55, 49, 65],
       [19, 68, 44, 90, 21],
       [77, 20, 86, 52, 63],
       [61, 82, 75, 57, 29]])

In [30]:
matrix[:,1::2]

array([[74,  3],
       [94, 49],
       [68, 90],
       [20, 52],
       [82, 57]])

In [31]:
np.mean(matrix[0])

55.6

In [35]:
import csv

arreglo=np.array([])
type(arreglo)
#with open("C:\\Users\\usuario\\Dropbox\\sena2025\\Trimestre1-Febrero10-Abril25\\2996881_Analitica\\datos2.csv") as mycsv:
with open("employees.csv") as mycsv:
    data=csv.reader(mycsv)
    print(data)
    print(type(data))
    for x in data:
        print(x)
        arreglo=np.append(arreglo,x)
    
print(arreglo)

<class '_csv.reader'>
['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER', 'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID', 'DEPARTMENT_ID']
['198', 'Donald', 'OConnell', 'DOCONNEL', '650.507.9833', '21-JUN-07', 'SH_CLERK', '2600', ' - ', '124', '50']
['199', 'Douglas', 'Grant', 'DGRANT', '650.507.9844', '13-JAN-08', 'SH_CLERK', '2600', ' - ', '124', '50']
['200', 'Jennifer', 'Whalen', 'JWHALEN', '515.123.4444', '17-SEP-03', 'AD_ASST', '4400', ' - ', '101', '10']
['201', 'Michael', 'Hartstein', 'MHARTSTE', '515.123.5555', '17-FEB-04', 'MK_MAN', '13000', ' - ', '100', '20']
['202', 'Pat', 'Fay', 'PFAY', '603.123.6666', '17-AUG-05', 'MK_REP', '6000', ' - ', '201', '20']
['203', 'Susan', 'Mavris', 'SMAVRIS', '515.123.7777', '07-JUN-02', 'HR_REP', '6500', ' - ', '101', '40']
['204', 'Hermann', 'Baer', 'HBAER', '515.123.8888', '07-JUN-02', 'PR_REP', '10000', ' - ', '101', '70']
['205', 'Shelley', 'Higgins', 'SHIGGINS', '515.123.8080', '07-JUN-02', 'AC_MGR', '1