In [1]:
import numpy as np
import random

# Arreglo de Tensores (●'◡'●)

In [2]:
mitensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(mitensor)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# Random.Randint (*/ω＼*)

In [3]:
# De un número
unnum = np.random.randint(0, 10)
print(unnum)
# Número aleatorio excluyendo 15
numal = np.random.randint(5, 15)
print(numal)
# Vector 3x3 
vec=np.random.randint(0, 50, size=(3, 3))
print(vec)

2
9
[[ 6 46 45]
 [10  6 42]
 [43  7  7]]


# Random ᓚᘏᗢ
Random tiene el valor 0 como el más pequeño y 1 como el más grande, nos da valores en ese rango. Si quisieramos convertirlo en un número entero, tendríamos que multiplicarlo por 100.

In [7]:
x = random.random()
print(x*100)

50.707387844159456


# Ejercicio
El número de filas y columnas debe ser ingresado por el usuario.

In [8]:
filas = int(input("Número de filas: "))
columnas = int(input("Número de columnas: "))
vec = np.random.randint(0, 50, size=(filas, columnas))
print(vec)


[[17 31]
 [46 39]
 [43 49]
 [37 32]
 [25 44]
 [ 8 39]
 [14 30]
 [19 39]
 [44  3]
 [ 3 12]
 [49  6]
 [ 4  1]
 [37 42]
 [38  5]
 [ 2 33]
 [19  1]
 [31 16]
 [21 47]
 [ 3 13]
 [27 28]]


Usar reshape y append dependiendo del caso. 

In [11]:
def mimatriz(filas, columnas):
    total_elementos = filas * columnas
    vec = np.random.randint(0, 50, size=total_elementos)
    if vec.size != total_elementos:
        if vec.size > total_elementos:
            vec = vec[:total_elementos]
        elif vec.size < total_elementos:
            vec = np.append(vec, np.random.randint(0, 50, size=(total_elementos - vec.size)))
    vec = vec.reshape(filas, columnas)

    return vec

filas = int(input("Introduce el número de filas: "))
columnas = int(input("Introduce el número de columnas: "))

matriz = mimatriz(filas, columnas)

print("Tu Matriz:")
print(matriz)

Tu Matriz:
[[45 22 48 37 34  6 22  5 42 26 33 24  8  6 25  0 20 31 46 35 12 24 21 31
  41 35  6 43 40 47 45  4 24 13 38 45  4 29 44  0 31 41 26  6 45 44 29 18
  34 24]
 [26 28 28 32 35 47 16 25 21  2 24  3 17 40 35 24 32 16  4 37 17 47 45 25
   5 15  7 31 32 22 26  8 33 36 38 18 18 37 25 44 19 19 42 29 38 10  5 13
  33  0]
 [46 12 36 39 25 10 49 45 14 43 23 14 49 17 27 26 13 10 12 26 13 28 42 46
   4 37 44 26 43 30 18 42 19 17 16  8 44 17 35 20 24 41 34 12 39 25 46  7
   9 24]
 [16 34 27  2 11 23 30 26 35 42 36 22 12 43 45 38 33 33 32  6 40 31 36 22
  34  9  3  8 30  6 20 14 44 22 44  7 14 40 24 30 16 22 32 25 40 23  1 49
  19  4]
 [18  5 25 10 28  4 15 13 16 39  7 36  6 40 16 10 26  1  5 23 46  4 33 28
  33  8 12 39 24 33 35 45 26 14 32 36 46 19  6 41 32 28 43 19 46 11 12 31
   4  6]
 [10 31 22 16 15 17 15 18 16 29 40  4 13 18 20 49 48 28 23  5 12 18 22 10
  22 25 41  8 21 44 35  7 35 31 32 41 16 36 34 44 48  3  9 28 40  7 10 46
  23  8]
 [46 32 23 23 32 21 35 22 34 29 43 15 29 34 49 